export enum PerformanceMetric {
    Element = 'element',
    Event = 'event',
    FirstInput = 'first-input',
    LargestContentfulPaint = 'largest-contentful-paint',
    LayoutShift = 'layout-shift',
    LongAnimationFrame = 'long-animation-frame',
    Longtask = 'longtask',
    Navigation = 'navigation',
    Paint = 'paint',
    Resource = 'resource',
    FirstPaint = 'first-paint',
    FirstContentfulPaint = 'first-contentful-paint',
    VisibilityState = 'visibility-state',
}
